from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent


# ============================================================
# Detector
# ============================================================

DETECTOR_PIXEL_COUNT = 2048


# ============================================================
# Original notebook SDF settings
# ============================================================

# Note:
# ib_region_size = 20 produces:
#
#     peak - 10 through peak + 10
#
# which is 21 pixels total.
IB_REGION_SIZE = 20


# In some calibration L0 file extra peaks observed for the 325 nm laser.
# These peaks were because of faulty laser and should not be considered as stray light.
APPLY_ORIGINAL_325NM_REPAIRS = True


# When duplicate source pixels exist, such as the two 488 nm blocks,
# the original notebook uses one 488 nm measurement.
#
# "first" reproduces that behavior using the first valid occurrence.
DUPLICATE_SOURCE_POLICY = "first"


# ============================================================
# Output
# ============================================================

SAVE_DIAGNOSTIC_PLOTS = True

OUTPUT_DPI = 180

# ============================================================
# Operational L0 batch correction
# ============================================================

# Directory containing stray-light-affected Pandora L0 files.
AFFECTED_L0_DIRECTORY = (
    PROJECT_ROOT
    / "data"
    / "stray_light_afftected_L0"
)


# Directory where corrected L0 files will be written.
CORRECTED_L0_DIRECTORY = (
    PROJECT_ROOT
    / "data"
    / "corrected_L0"
)

L0_FILE_PATTERN = "*.txt"

# To correct only SQ:
#     L0_ROUTINE_TYPES = ("SQ",)
#
# To correct only SS:
#     L0_ROUTINE_TYPES = ("SS",)
L0_ROUTINE_TYPES = ("SS")


# Example:
#     Pandora63s1_GreenbeltMD_20250430_L0.txt
#
# becomes:
#     Pandora63s1_GreenbeltMD_20250430_L0_corrected.txt
CORRECTED_L0_SUFFIX = "_corrected"


# Correction matrix generated by test_matrix_builder.py.
CORRECTION_MATRIX_FILE = (
    PROJECT_ROOT
    / "outputs"
    / "straylight_matrix_original_method"
    / f"P63_corr_mat_ib{IB_REGION_SIZE}.csv"
)


# Original notebook L0 structure.
L0_HEADER_LINE_COUNT = 44

L0_SPECTRUM_START_COLUMN = 24

L0_SPECTRUM_END_COLUMN_EXCLUSIVE = 2072


# Filterwheel #2 position identifying dark measurements.
DARK_FILTERWHEEL_2_POSITION = "3"


# Original notebook condition:
#
#     filterwheel #1 < 9
MAXIMUM_VALID_FILTERWHEEL_1_POSITION = 9


# When no matching dark exists, reproduce the notebook behavior by
# using a zero dark spectrum.
USE_ZERO_DARK_WHEN_MISSING = True


# Write corrected detector counts as integers.
L0_OUTPUT_DECIMAL_PLACES = 0


# Continue processing remaining files if one file fails.
CONTINUE_BATCH_AFTER_ERROR = True